# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUMYdy9fiwNp7_1pSh4WPROxeK5DLjRC
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("fifa_world_cup_2026_player_performance.csv")
df.head()
df.info()
df.describe()
df.isnull().sum()

